# Generated by Django 3.1 on 2020-09-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_matchreportinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreportinput',
            name='adjective2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchreportinput',
            name='animals',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchreportinput',
            name='fav_drink',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchreportinput',
            name='golf_saying',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchreportinput',
            name='group_noone_likes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchreportinput',
            name='jobs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchreportinput',
            name='lyric',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchreportinput',
            name='office_perk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchreportinput',
            name='old_saying',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchreportinput',
            name='recent_news',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchreportinput',
            name='sports_expression',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
