# Generated by Django 3.1 on 2020-09-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200928_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchreportinput',
            old_name='name',
            new_name='report_name',
        ),
    ]
