# Generated by Django 3.1 on 2020-09-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200928_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreportinput',
            name='fav_drink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchreportinput',
            name='golf_saying',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchreportinput',
            name='group_noone_likes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchreportinput',
            name='jobs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchreportinput',
            name='lyric',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchreportinput',
            name='office_perk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchreportinput',
            name='old_saying',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchreportinput',
            name='recent_news',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchreportinput',
            name='sports_expression',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
