# Generated by Django 3.1 on 2020-10-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200929_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsRoundModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locator', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
