# Generated by Django 3.1 on 2020-10-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_teamsroundmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamsroundmodel',
            options={},
        ),
        migrations.RenameField(
            model_name='teamsroundmodel',
            old_name='score',
            new_name='score1',
        ),
        migrations.RenameField(
            model_name='teamsroundmodel',
            old_name='team_name',
            new_name='team_name1',
        ),
        migrations.AddField(
            model_name='teamsroundmodel',
            name='score2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsroundmodel',
            name='team_name2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
