# Generated by Django 3.1 on 2020-10-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201014_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsroundmodel',
            name='holes1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsroundmodel',
            name='holes2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
